headers = {
	'Accept': '*/*',
	'Accept-Language': 'en-US,en;q=0.9,uk-UA;q=0.8,uk;q=0.7,ru;q=0.6,zh-CN;q=0.5,zh;q=0.4',
	'Connection': 'keep-alive',
	'Lang': 'en',
	'Origin': 'https://telegram.blum.codes',
	'Sec-Ch-Ua': '"Chromium";v="126", "Google Chrome";v="126", "Not;A Brand";v="99"',
	'Sec-Ch-Ua-Mobile': '?1',
	'Sec-Ch-Ua-Platform': '"Android"',
	'Sec-Fetch-Dest': 'empty',
	'Sec-Fetch-Mode': 'cors',
	'Sec-Fetch-Site': 'same-site',
	'User-Agent': 'Mozilla/5.0 (Linux; Android 9; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.6367.82 Mobile Safari/537.36',
	'X-Requested-With': 'org.telegram.messenger.web',
}
